### ISSUE TITLE
No content for violations

### ISSUE THREAD

**Issue by cweiske** [devever/violation-reports#1]
I would have expected to see content when clicking on the [OSIGNAPP — All programs must be signed by Apple](https://violations.devever.net/violations/8cdd5081767054efb943959bf566ac6a) link on the [All IOS devices](https://violations.devever.net/products/8191991588b25523a38744b6ce6bd23c) page.

All "deep" pages seem to have no content.

**Comment by hlandau** [comment]
Oops, this is a bug. Investigating.

**Comment by hlandau** [comment]
Fixed. May have to refresh some pages. Thanks for the report.
